;;; themes/custom-light-theme.el -*- lexical-binding: t; -*-
;;; commentary: catppuccin-latte based theme
(eval-when-compile
  (require 'cl-lib))
(require 'autothemer)
(autothemer-deftheme
	catppuccin-latte "A theme based on catppuccin's amazing color scheme")
 ((((class color) (min-colors #xFFFFFF))        ; col 1 GUI/24bit
   ((class color) (min-colors #xFF)))           ; col 2 Xterm/256

  (rosewater  "#dc8a78" "#ffffff")
  (flamingo   "#dd7878" "#ffd7df")
  (pink       "#ea76cb" "#d7afaf")
  (mauve      "#8839ef" "#d7afd7")
  (red        "#d20f39" "#ff87af")
  (dark-red   "#311c22" "#311c22")
  (maroon     "#e64553" "#ffafaf")
  (peach      "#fe640b" "#ffaf87")
  (yellow     "#df8e1d" "#ffd7af")
  (green      "#40a02b" "#87afaf")
  (teal       "#179299" "#afd7d7")
  (sapphire   "#209fb5" "#afffff")
  (blue       "#1e66f5" "#00d7ff")
  (lavender   "#7287fd" "#d7d7ff")
  (text       "#4c4f69" "#ffffff")
  (subtext1   "#5c5f77" "#ffffff")
  (subtext0   "#6c6f85" "#ffffff")
  (overlay2   "#7c7f93" "#ffffff")
  (overlay1   "#8c8fa1" "#ffffff")
  (overlay0   "#9ca0b0" "#ffffff")
  (surface2   "#acb0be" "#ffffff")
  (surface1   "#bcc0cc" "#ffffff")
  (surface0   "#ccd0da" "#ffffff")
  (base       "#eff1f5" "#ffffff")
  (mantle     "#e6e9ef" "#ffffff")
  (crust      "#dce0e8" "#ffffff"))

((default                              (:background base :foreground text))
  (border                               (:foreground crust))
  (bookmark-face                        (:foreground red))
  (button                               (:foreground blue))
  (child-frame                          (:foreground mantle))
  (child-frame-border                   (:foreground mantle))
  (cursor                               (:background yellow :foreground crust))
  (error                                (:foreground red))
  (link                                 (:foreground blue))
  (fringe                               (:foreground surface0))
  (file-name-shadow                     (:foreground overlay2))
  (glyph-face                           (:background red :foreground overlay0))
  (glyphless-char                       (:foreground overlay2))
  (header-line                          (:background mantle :height 0.8 :box (:line-width 6 :color mantle)))
  (highlight                            (:background mantle :foreground blue :distant-foreground crust))
  (hl-line                              (:background surface0))
  (homoglyph                            (:foreground teal))
  (line-number                          (:foreground surface1))
  (line-number-current-line             (:background surface0 :foreground mauve :bold t))
  (match                                (:background yellow :foreground crust))
  (menu                                 (:foreground rosewater))
  (fill-column-indicator                (:foreground surface0))

  (mode-line                            (:background mantle :foreground text :box (:line-width 1 :color crust)))
  (mode-line-active                     (:inherit 'mode-line))
  (mode-line-inactive                   (:background surface0 :foreground subtext0))
  (mode-line-highlight                  (:foreground text))
  (mode-line-buffer-id                  (:foreground lavender))
  (mode-line-emphasis                   (:foreground blue))

  (numbers                              (:background peach))
  (region                               (:background lavender :foreground crust))
  (tooltip                              (:background overlay2 :foreground crust))
  (shadow                               (:foreground overlay2))
  (success                              (:foreground green))
  (vertical-border                      (:foreground crust))
  (warning                              (:foreground yellow))
  (window-divider                       (:foreground base :distant-foreground mantle))

  (whitespace-newline                   (:foreground surface2))
  (whitespace-space                     (:foreground surface2))
  (whitespace-trailing                  (:foreground mantle :background red))

  (minibuffer-prompt-end                (:foreground blue))
  (minibuffer-prompt                    (:foreground blue))
  (epa-mark                             (:foreground pink))
  (dired-mark                           (:foreground pink))
  (dired-ignored                        (:background peach))

  (minimap-active-region-background     (:background surface1))

  (iedit-occurrence                     (:background blue :foreground crust))
  (iedit-read-only-occurrence           (:background green :foreground crust))

  (trailing-rosewaterspace              (:background surface1))

  (org-done                             (:foreground overlay2))
  (org-code                             (:background crust))
  (org-meta-line                        (:background surface1 :foreground blue))
  (org-block                            (:background crust))
  (org-block-begin-line                 (:background crust :foreground overlay2))
  (org-block-end-line	                (:background crust :foreground overlay2))
  (org-headline-done                    (:foreground overlay2 :strike-through t))
  (org-todo                             (:foreground green :bold t))
  (org-headline-todo                    (:foreground base))
  (org-upcoming-deadline                (:foreground red))
  (org-footnote                         (:foreground green))
  (org-indent                           (:foreground base))
  (org-hide	                            (:foreground base))
  (org-date                             (:foreground overlay2))
  (org-ellipsis                         (:foreground overlay2 :bold t))
  (org-level-1                          (:foreground red :height 1.3 :bold t))
  (org-level-2                          (:foreground mauve :height 1.15 :bold t))
  (org-level-3                          (:foreground flamingo :height 1.05))
  (org-level-4                          (:foreground teal))
  (org-level-5                          (:foreground pink))
  (org-level-6                          (:foreground yellow))
  (org-level-7                          (:foreground peach))
  (org-level-8                          (:foreground maroon))

  (show-paren-match						(:background maroon :foreground crust :bold t))
  (show-paren-match-expression			(:background maroon :foreground crust :bold t))
  (show-paren-mismatch					(:background red))

  (completions-annotations                      (:foreground subtext0 :italic t))
  (completions-highlight                        (:foreground blue :italic t))
  (completions-common-part                      (:foreground yellow :distant-foreground crust :distant-background green :bold t :italic t))
  (completions-first-difference                 (:foreground red))
  (consult-file                                 (:foreground subtext0 :distant-foreground crust))
  (consult-preview-line                         (:background crust))

  (diff-added (:background green :foreground text))
  (diff-changed (:background yellow :foreground crust))

  (dashboard-items-face								(:weight 'light :height 150))
  (dashboard-banner-logo-title						(:weight 'thin :height 320))
  (dashboard-heading								(:foreground subtext1 :weight 'thin :height 170))
  (dashboard-no-items-face							(:foreground overlay2))

  (evil-ex-lazy-highlight           (:foreground crust :background yellow :bold t))
  (evil-ex-substitute-matches       (:foreground red :strike-through t))
  (evil-ex-substitute-replacement   (:foreground blue :bold t))
  (evil-search-highlight-persist-highlight-face (:background yellow))
  (evil-quickscope-first-face       (:foreground yellow :underline t))
  (evil-quickscope-second-face      (:foreground peach :underline t))
  (evil-goggles-default-face        (:background peach))
  (evil-goggles-join-face           (:foreground blue))
  (evil-goggles-delete-face         (:background red))
  (evil-goggles-paste-face          (:background green))
  (evil-goggles-indent-face         (:background subtext0))
  (evil-goggles-set-marker-face     (:foreground red :background red))
  (evil-goggles-yank-face           (:foreground blue :background blue))

  (ansi-color-crust (:background crust))

  (term (:background crust :foreground text))
  (term-color-blue (:background blue :foreground blue))
  (term-color-bright-blue (:inherit 'term-color-blue))
  (term-color-red (:background red :foreground red))
  (term-color-bright-red (:background maroon :foreground maroon))
  (term-color-yellow (:background yellow :foreground yellow))
  (term-color-bright-yellow (:background yellow :foreground yellow))

  (term-color-green (:background green :foreground green))
  (term-color-bright-green (:inherit 'term-color-green))

  (term-color-bright-crust (:background mantle :foreground red))
  (term-color-rosewater (:background text :foreground text))
  (term-color-bright-rosewater (:background rosewater :foreground rosewater))
  (term-color-cyan (:background sky :foreground sky))
  (term-color-bright-cyan (:background sky :foreground sky))
  (term-color-magenta (:background mauve :foreground mauve))
  (term-color-bright-magenta (:background mauve :foreground mauve))
  (term-underline (:background mauve :foreground blue))

  (vterm-color-crust (:background mantle :foreground mantle))
  (vterm-color-blue (:background blue :foreground blue))
  (vterm-color-cyan (:background sky :foreground sky))
  (vterm-color-green (:background green :foreground green))
  (vterm-color-magenta (:background maroon :foreground maroon))
  (vterm-color-yellow (:background peach :foreground yellow))
  (vterm-color-red (:background red :foreground red))
  (vterm-color-rosewater (:background text :foreground text))

  (bm-fringe-face                           (:background red :foreground crust))
  (bm-fringe-persistent-face                (:background red :foreground crust))

  )

(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'catppuccin-latte)
;;; catppuccin-latte-theme.el ends here
